#Engagement API ------------------------
engagement_settings:
  name: my-metrics-data           #Session name for data set, used to label output.
  endpoint: historical            #options: totals, 28hr, historical.
  inbox: ./inbox                  #Tweet inbox (HPT gz files? Search JSON?, CSV database dump?)
  outbox: ./outbox                #Engagement API output is written here.
  name_based_folders: true        #Build folder and file names based on 'name'.
  max_top_tweets: 10              #Set to zero to turn 'top Tweet' processing off.
  start: 201603021200             #(UTC) for /historical endpoint, defaults to now - 28 days, or 'end' - 28 days..
  #end:                           #(UTC) for /historical endpoint, defaults to now, or 'start' + 28 days.
  save_api_responses: true       #Saves Engagement API responses to a 'api_responses' subfolder of the 'outbox'.
  verbose: true                   #More status fyi written to system out while running.
  rate_limit_requests: 2          #Set these to help avoid request rate limits.
  rate_limit_seconds: 60          #Time between calls equals rate_limit_seconds/rate_limit_requests (60/4 = 15) seconds.

engagement_types: #Order here is echoed in output.
  impressions: true
  engagements: true
  retweets: true
  favorites: true
  replies: true
  url_clicks: true
  email_tweet: true
  user_follows: true
  user_profile_clicks: true
  hashtag_clicks: true
  video_views: false
  detail_expands: false
  media_clicks: false
  permalink_clicks: false
  app_opens: false
  app_install_attempts: false

engagement_groupings:  
  by_type:  #Grand totals.
    - engagement.type
  by_tweet_type: #Needed for surfacing Top Tweets. I.e., the 'top Tweet' code depends on this specific API output.
    - tweet.id
    - engagement.type
  timeseries_hourly:
    - tweet.id
    - engagement.type
    - engagement.day
    - engagement.hour
  timeseries_daily:
    - tweet.id
    - engagement.type
    - engagement.day
  hour_of_day:
    - tweet.id
    - engagement.type
    - engagement.hour

logging:
  name: engagement_app.log
  log_path: ./log
  warn_level: debug
  size: 1 #MB
  keep: 2
